# =============================================================================
# Datasource
# =============================================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=032014
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres


# =============================================================================
# Schema initialization
# =============================================================================
#quarkus.datasource.devservices.init-script-path=db/schema.sql
# =============================================================================
# Security: Form-Based Authentication
# =============================================================================

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/login
quarkus.http.auth.form.error-page=/login?error=true
quarkus.http.auth.form.landing-page=/homepage
quarkus.http.auth.form.cookie-name=quarkus-credential
quarkus.http.auth.form.timeout=PT30M

# =============================================================================
# Security: Elytron JDBC Realm
# =============================================================================
quarkus.security.jdbc.enabled=true

quarkus.security.jdbc.principal-query.sql=SELECT u.password FROM "user" u WHERE u.username=?
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.bcrypt-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=1
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups

# =============================================================================
# Authorization Policies
# =============================================================================
#quarkus.http.auth.permission.public.paths=/login,/register,/q/*,/css/*,/js/*
#quarkus.http.auth.permission.public.policy=permit

#quarkus.http.auth.permission.authenticated.paths=/app/*
#quarkus.http.auth.permission.authenticated.policy=authenticated

# =============================================================================
# Qute
# =============================================================================
quarkus.qute.content-types.html=text/html